// This file is auto-generated by build/generate-assets.js
// Do not edit directly - edit templates/*.html and Assets/prompt-builder.css instead

// HTML Templates
namespace Templates {
    export const danbooruLink = `<a
  href="https://danbooru.donmai.us/wiki_pages/{{encodedTag}}"
  target="_blank"
  class="pb-item-card-link"
  title="View on Danbooru Wiki"
  onclick="event.stopPropagation()"
  >🔗</a
>
`;

    export const error = `<div class="pb-error">
    <strong>Error:</strong> {{errorMessage}}
</div>
`;

    export const groupNav = `<ul class="pb-nav-list">
    {{groups}}
</ul>`;

    export const group = `<li>
  <div
    class="pb-nav-group {{active}}"
    data-path="{{groupName}}"
    data-group-path="{{groupPath}}"
    data-parent-path=""
  >
    <span class="pb-nav-label">{{groupName}}</span>
  </div>
  {{subgroups}}
</li>
`;

    export const itemCard = `<div
  class="pb-item-card {{selected}}"
  data-value="{{value}}"
>
  <span class="pb-item-card-text">{{value}}</span>
  {{link}}
</div>
`;

    export const mainContainer = `<div class="pb-prompt-builder-container">
    <div class="pb-nav-panel" id="pb-nav-panel">
        <div class="pb-nav-search-box">
            <input type="text" 
                   class="pb-nav-search-input" 
                   placeholder="Select a category first..." 
                   value="{{searchFilter}}"
                   id="pb-nav-search-input">
        </div>
        <ul id="pb-nav-list" class="pb-nav-list"></ul>
    </div>
    <div class="pb-resize-handle" id="pb-resize-handle"></div>
    <div class="pb-content-panel">
        <div class="pb-selected-tags-container">
            <div class="pb-settings-gear-wrapper">
                <div class="batch-gear-button pb-settings-gear" id="pb-settings-button" title="Settings">&#9881;</div>
            </div>
            <button class="pb-action-button" id="pb-copy-button" title="Copy to clipboard">⿻</button>
            <button class="pb-action-button" id="pb-clear-button" title="Clear all tags">✕</button>
            <button class="pb-action-button" id="pb-retry-button" title="Retry generation">↻</button>
            <button class="pb-action-button pb-random-mode-btn" id="pb-random-mode-btn" title="Add a random group — pick from multiple options at generation time">&#127922; Random</button>
            {{popoutButton}}
            <div class="pb-selected-tags" id="pb-selected-tags"></div>
        </div>
        <div class="pb-random-mode-controls" id="pb-random-mode-controls" style="display:none;">
            <span class="pb-random-mode-label" id="pb-random-mode-label">0 tags selected</span>
            <button class="pb-action-button pb-random-confirm-btn" id="pb-random-confirm-btn" disabled>&#10003; Confirm Group</button>
            <button class="pb-action-button pb-random-cancel-btn" id="pb-random-cancel-btn">&#10005; Cancel</button>
        </div>
        <div class="pb-items-container" id="pb-items-container">
            <div class="pb-items-grid"></div>
        </div>
    </div>
</div>
`;

    export const noSelection = `<div class="pb-no-selection">
    <h3>Welcome!</h3>
    <p>Select a category from the left panel to view tags</p>
</div>
`;

    export const noTagsSelected = `<span class="text-muted">No tags selected</span>`;

    export const popoutButton = `<button class="pb-action-button" id="pb-popout-button" title="Pop out to new window">⧉</button>`;

    export const popupWindow = `<!DOCTYPE html>
<html>
  <head>
    <title>Prompt Builder</title>
    {{stylesheets}}
  </head>
  <body>
    <div id="pb-popup-app"></div>
    <script>
      // Store state to restore after script loads
      window.promptBuilderState = {{state}};

      // Make parent window functions available
      window.genericRequest = function(...args) {
          return window.opener.genericRequest(...args);
      };

      // Expose SwarmUI functions from parent window
      if (window.opener.doPopover) {
          window.doPopover = function(...args) {
              return window.opener.doPopover(...args);
          };
      }

      if (window.opener.AdvancedPopover) {
          window.AdvancedPopover = window.opener.AdvancedPopover;
      }
    </script>
    <script src="/ExtensionFile/PromptBuilderExtension/Assets/prompt-builder.js?vary={{timestamp}}"></script>
    <script>
      // After the script loads, initialize with saved state
      window.addEventListener("load", () => {
        if (window.promptBuilderPopupInit) {
          window.promptBuilderPopupInit(window.promptBuilderState);
        }
      });
    </script>
  </body>
</html>
`;

    export const settingsModal = `<div class="sui-popover sui_popover_model" id="popover_pb_settings">
    <div class="pb-setting-item" title="Automatically trigger image generation when tags are added">
        <span class="form-check form-switch display-inline-block">
            <input type="checkbox" class="form-check-input" id="pb-setting-autogenerate">
            <label class="form-check-label" for="pb-setting-autogenerate">Auto-generate images</label>
        </span>
    </div>
    <div class="pb-setting-item sui-popover-inline-block" title="Minimum number of tags required before auto-generation triggers">
        <label for="pb-setting-autogenerate-threshold">Min tags:</label>
        <input type="number" id="pb-setting-autogenerate-threshold" class="pb-setting-number-input" min="1" max="20" value="3">
    </div>
    <div class="pb-setting-item" title="Show clickable links to Danbooru wiki for each tag">
        <span class="form-check form-switch display-inline-block">
            <input type="checkbox" class="form-check-input" id="pb-setting-danbooru-links">
            <label class="form-check-label" for="pb-setting-danbooru-links">Show Danbooru links</label>
        </span>
    </div>
    <div class="pb-setting-item" title="Enable console logging for debugging purposes">
        <span class="form-check form-switch display-inline-block">
            <input type="checkbox" class="form-check-input" id="pb-setting-debug-mode">
            <label class="form-check-label" for="pb-setting-debug-mode">Enable debug mode</label>
        </span>
    </div>
</div>

`;

    export const subgroup = `<div
  class="pb-nav-subgroup {{depthClass}} {{active}}"
  data-path="{{fullPath}}"
  data-parent-path="{{parentPath}}"
  data-group-path="{{groupPath}}"
>
  {{spacer}}
  <span class="pb-nav-label">{{subgroupName}}</span>
</div>
`;

    export const tagChipEditing = `<div
  class="pb-tag-chip pb-tag-chip-editing"
  data-index="{{index}}"
  data-tag="{{tag}}"
>
  <input
    type="text"
    class="pb-tag-chip-input"
    value="{{tag}}"
    data-index="{{index}}"
  />
</div>
`;

    export const tagChipRandom = `<div
  class="pb-tag-chip pb-tag-chip-random"
  draggable="true"
  data-index="{{index}}"
  data-tag="{{tag}}"
>
  <span class="pb-tag-chip-random-icon">&#127922;</span>
  <span class="pb-tag-chip-random-tags">{{tags}}</span>
</div>
`;

    export const tagChip = `<div
  class="pb-tag-chip"
  draggable="true"
  data-index="{{index}}"
  data-tag="{{tag}}"
>
  <span>{{tag}}</span>
</div>
`;

}

